language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
before_script:
  - python manage.py migrate
script:
  - pytest
env:
  - ENVIRONMENT=travis SECRET_KEY=7f6245e78d16c87bb4bc0939