# Generated by Django 3.0.7 on 2020-06-11 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('errorcentralapp', '0002_appexception'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='exception',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='errorcentralapp.AppException'),
            preserve_default=False,
        ),
    ]
