# Generated by Django 3.0.7 on 2020-07-13 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('errorcentralapp', '0003_errorlog_exception'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='errorlog',
            name='source',
        ),
        migrations.AddField(
            model_name='errorlog',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='errorcentralapp.Agent'),
            preserve_default=False,
        ),
    ]
